name: auth-service

services:

  auth-service-db:
    image: postgres:16
    container_name: auth-service-db
    environment:
      - POSTGRES_USER=${AUTH_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_SERVICE_POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-auth:
    container_name: kafka-auth
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  
  
#  auth-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: auth-service
#    ports:
#      - "9000:9000"
#    environment:
#      - AUTH_SERVICE_POSTGRES_DB=${AUTH_SERVICE_POSTGRES_DB}
#      - AUTH_SERVICE_POSTGRES_USER=${AUTH_SERVICE_POSTGRES_USER}
#      - AUTH_SERVICE_POSTGRES_PASSWORD=${AUTH_SERVICE_POSTGRES_PASSWORD}
#      - AUTH_SERVICE_POSTGRES_PORT=${AUTH_SERVICE_POSTGRES_PORT}
#      - AUTH_SERVICE_POSTGRES_HOST=${AUTH_SERVICE_POSTGRES_HOST}
#      - AUTH_SERVICE_KAFKA_HOST=${AUTH_SERVICE_KAFKA_HOST}
#      - AUTH_SERVICE_KAFKA_PORT=${AUTH_SERVICE_KAFKA_PORT}
#      - SPRING_PROFILES_ACTIVE=docker
#      - SECRET_KEY=${SECRET_KEY}
#    depends_on:
#      - auth-service-db
#      - kafka-auth


volumes:
  pgdata:
