CREATE TABLE refresh_tokens
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_dttm TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version      BIGINT DEFAULT 1 NOT NULL
        CONSTRAINT refresh_tokens_version_positive CHECK (version > 0),
    device_id    VARCHAR(255) NOT NULL,
    expires_at   TIMESTAMP(6) NOT NULL,
    token_hash   VARCHAR(128) NOT NULL
        CONSTRAINT refresh_tokens_token_hash_unique UNIQUE,
    user_id      BIGINT NOT NULL,
    CONSTRAINT refresh_tokens_user_device_unique UNIQUE (user_id, device_id),
    CONSTRAINT refresh_tokens_user_fk FOREIGN KEY (user_id) REFERENCES user_credentials(id)
);

COMMENT ON COLUMN refresh_tokens.id IS 'Identifier';
COMMENT ON COLUMN refresh_tokens.created_dttm IS 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';
COMMENT ON COLUMN refresh_tokens.updated_at IS 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';
COMMENT ON COLUMN refresh_tokens.version IS 'large range number from -9223372036854775808 to +9223372036854775807';
COMMENT ON COLUMN refresh_tokens.device_id IS 'Device ID (could be UUID or any unique value)';
COMMENT ON COLUMN refresh_tokens.expires_at IS 'Refresh token expiration time';
COMMENT ON COLUMN refresh_tokens.token_hash IS 'Hashed refresh token';
COMMENT ON COLUMN refresh_tokens.user_id IS 'Foreign key to user_credentials';

