CREATE TABLE user_credentials
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_dttm  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version       BIGINT DEFAULT 1 NOT NULL
        CONSTRAINT user_credentials_version_positive CHECK (version > 0),
    email         VARCHAR(50) NOT NULL
        CONSTRAINT user_credentials_email_unique UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(30) NOT NULL
        CONSTRAINT user_credentials_role_check CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN'))
);

COMMENT ON COLUMN user_credentials.id IS 'Identifier';
COMMENT ON COLUMN user_credentials.created_dttm IS 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';
COMMENT ON COLUMN user_credentials.updated_at IS 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';
COMMENT ON COLUMN user_credentials.version IS 'large range number from -9223372036854775808 to +9223372036854775807';
COMMENT ON COLUMN user_credentials.email IS 'User email, used as login. Unique.';
COMMENT ON COLUMN user_credentials.password_hash IS 'User password hashed.';
COMMENT ON COLUMN user_credentials.role IS 'User role, e.g., ROLE_USER, ROLE_ADMIN.';

